# Generated by Django 4.0.5 on 2022-06-20 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roulette.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.JSONField(default=roulette.models.round_jsonfield_default, verbose_name='Remained slots')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('spin_round', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='roulette.round', verbose_name='Round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Spin',
                'verbose_name_plural': 'Spins',
                'ordering': ['-id'],
            },
        ),
    ]
