# Generated by Django 4.0.5 on 2022-06-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roulette', '0003_alter_spin_spin_round_alter_spin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='participants',
        ),
        migrations.AlterField(
            model_name='round',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is deleted'),
        ),
    ]
