version: '3.9'

services:
  django:
    build:
      context: .
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:${HTTP_PORT}
      "
    volumes:
      - ./spinwheel:/spinwheel
      - django:/vol/web/static
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    env_file: .env
    depends_on:
      - db

  test:
    build:
      context: .
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py test
      "
    volumes:
      - ./spinwheel:/spinwheel
    env_file: .env
    depends_on:
      - db

  filldb:
    build: .
    command: >
      sh -c "
        python manage.py wait_for_db &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py loaddata fixtures/dev.json
      "
    volumes: 
      - ./spinwheel:/spinwheel
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

volumes:
  django:
  postgres-data:
